ALTER TABLE jobs
  ADD COLUMN IF NOT EXISTS range_start TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS range_end_mode VARCHAR(16) NOT NULL DEFAULT 'NOW',
  ADD COLUMN IF NOT EXISTS range_end TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS min_chunk_duration_hours INT NOT NULL DEFAULT 24,
  ADD COLUMN IF NOT EXISTS max_chunk_duration_hours INT NOT NULL DEFAULT 168;
