CREATE TYPE job_run_mode AS ENUM ('TEST', 'PRODUCTION');

ALTER TABLE jobs ADD COLUMN run_mode job_run_mode NOT NULL DEFAULT 'TEST';

ALTER TABLE connections ADD COLUMN sandbox BOOLEAN NOT NULL DEFAULT FALSE;
